#  define on which event, here a push
on:
  push:
  # and the target with some regex to match our specific  branch names
    branches:
      - master
      - 'JAHIA-[0-9]-[0-9]-[0-9]-X-BRANCH'
      - '[0-9]_[0-9]_x'
      - '[0-9]-[0-9]-X-BRANCH'
  pull_request:
    types: [opened,synchronized,reopened]

# We can now build our job
# giving a name to your  workflow
name: Analyze branch
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository on master'
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      # Use an existing action, you can look in the market place to find what you need and how to use  it, to setup the sonar scanner
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONAR_URL }}
          login: ${{ secrets.SONAR_TOKEN }}
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
